### ISSUE TITLE
[GitHub Container Registry] Create init-ceremony image

### ISSUE THREAD

**Issue by Klazomenai** [clearmatics/init-ceremony#1]
# Problem
As part of the migration from DockerHub to GitHub Container Registry, this issue will outline configuration steps needed for the move.

# Implementation
This issue will outline configuration steps for the the `container/settings` section, extend GitHub Actions to direct the artefacts to the new registry and update any related documentations. The detailed steps can be found in the acceptance criteria below.

# Acceptance Criteria
- [x] Issue GitHub PAT from @clearmaticsrobot with r/w access to packages. Named: `GitHub Actions init-ceremony`
- [x] Add to GitHub Secret `CR_PAT`
- [x] Add to Dockerfile the label
  ```
  LABEL org.opencontainers.image.source https://github.com/clearmatics/autonity-init
  ```
- [x] Pull, create new tag and push `latest` [needed for enabling the container service for this repository]
  ```
  docker pull clearmatics/init-ceremony:latest
  docker tag clearmatics/init-ceremony:latest ghcr.io/clearmatics/init-ceremony:latest
  docker push ghcr.io/clearmatics/init-ceremony:latest
  ```
- [x] As the `clearmaticsrobot` user, set public access for container repository [clearmatics/init-ceremony](https://github.com/orgs/clearmatics/packages/container/init-ceremony/settings)
- [x] Create GitHub Action for building docker image
- [x] Update other references which point to DockerHub to point to the new GHCR location
- [x] The following versions exist in the [new repository location](https://github.com/orgs/clearmatics/packages/container/package/init-ceremony): `latest`, `v1.0.0`

# Future Steps
- Ensure pipelines are still functioning

**Comment by eastata** [comment]
Related: 
Update `autonity` helm chart
