### ISSUE TITLE
Mark repository ready for archive

### ISSUE THREAD

**Issue by Klazomenai** [clearmatics/init-ceremony#3]
### Description
With recent Helm chart updates, this repository now legacy. The Bakerloo network currently still requires access to assets, so assets will be archived only once the Bakerloo network is running the latest Helm Chart. DevNet has already been covered.

### Pre-requisites
- [x] DevNet to run Helm chart >= `1.6.1`
- [x] Bakerloo to run Helm chart >= `1.6.1`

### Acceptance criteria
- [x] Delete all GitHub Container Registry older style packages
- [x] Delete all GitHub Packages
- [x] Update Readme with archive status
- [x] Notify Org owner to archive this repository

**Comment by raj-shekhar1** [comment]
FYA @Klazomenai
